/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppChildrenRouteRouteImport } from './routes/app.childrenRoute'
import { Route as DeepNestedRouteRouteImport } from './routes/deep.nested.route'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChildrenRouteRoute = AppChildrenRouteRouteImport.update({
  id: '/childrenRoute',
  path: '/childrenRoute',
  getParentRoute: () => AppRouteRoute,
} as any)
const DeepNestedRouteRoute = DeepNestedRouteRouteImport.update({
  id: '/deep/nested',
  path: '/deep/nested',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/deep/nested': typeof DeepNestedRouteRoute
  '/app/childrenRoute': typeof AppChildrenRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/deep/nested': typeof DeepNestedRouteRoute
  '/app/childrenRoute': typeof AppChildrenRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/deep/nested': typeof DeepNestedRouteRoute
  '/app/childrenRoute': typeof AppChildrenRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/deep/nested' | '/app/childrenRoute'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/deep/nested' | '/app/childrenRoute'
  id: '__root__' | '/' | '/app' | '/deep/nested' | '/app/childrenRoute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DeepNestedRouteRoute: typeof DeepNestedRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/childrenRoute': {
      id: '/app/childrenRoute'
      path: '/childrenRoute'
      fullPath: '/app/childrenRoute'
      preLoaderRoute: typeof AppChildrenRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/deep/nested': {
      id: '/deep/nested'
      path: '/deep/nested'
      fullPath: '/deep/nested'
      preLoaderRoute: typeof DeepNestedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppChildrenRouteRoute: typeof AppChildrenRouteRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChildrenRouteRoute: AppChildrenRouteRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DeepNestedRouteRoute: DeepNestedRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
